### ISSUE TITLE
The IPLD ROADMAP

### ISSUE THREAD

**Issue by daviddias** [ipld/specs#41]
> C&P from https://github.com/ipfs/specs/issues/115 //cc @nicola 

Let's collect the IPLD bigger picture here

cc (@jbenet, @mildred, @dignifiedquire, @stebalien)
- [x] **new org** -  (https://github.com/ipfs/specs/issues/128): move implementations and specs under https://github.com/ipld
- [ ] **spec refining**:
  - [ ] **cycles/relative links** (https://github.com/ipld/specs/issues/1) -  If we add relative links in merkle links, then we can have mutual relationships.
  - [ ] **attributes in /** (https://github.com/ipld/specs/issues/2)
  - [ ] **Find a name space**: '/ipld' or '/ipfs' or just hash
  - [ ] **Use of IPLD pointers as links** (https://github.com/ipld/specs/issues/3): right now implementation only support hashes
- [ ] **query** - way to find attributes (or value) that is easy to express (instead of programmatically traversing a tree)
  - [ ] **selectors** (https://github.com/ipfs/2016-Q3-Workshop/issues/5 and https://github.com/ipfs/notes/issues/12)
    - design/find a nice language
    - research on relational db in directed graph
    - must be simple, fast, reliable
    - must create virtual graphs
  - [ ] **full query language** (later 2017) - more complex query than simple selectors
    - could be unreliable (unless specified)
    - design a query language
    - should create virtual graphs
- [ ] **programmable data** & **transformations** (https://github.com/ipfs/specs/issues/102)
  - [ ] IPC (inter-planetary computation) - decentralized compilable computation
  - [ ] Transformation - subclass of IPC (but pure, functional and return a graph/value)
  - [ ] IPLD objects can be input to IPC or can define transformations in the data itself
  - talk to the functional programming language research folks
  - could be writing contracts & smart signature (?)
    - infinite computation should be possible
    - possible languages to consider
      - web assembly
      - haskell
      - javascript
      - morte
      - LLVM IR
        - maybe there is a need for **multipl** (multi-programming or multi-language)
- [ ] **verifiable computation on IPLD**
  - consider simplifying lambda auth as a lib in haskell
  - consider extending IPRS, IPC(IPLD)
- [ ] **abstract paths** (https://github.com/ipfs/specs/issues/91)
  - should be able to express abstract paths via transformations
  - could do sharding (consequence of programmable data)
    - is sharing application specific?
## 

I will clean this up in different issues

**Comment by samsends** [comment]
I am very interested in Transformations / IPC, however, it is proving extremely difficult to find reading material. Can anyone point me in the right direction? Kindly, Sam Sendelbach

**Comment by daviddias** [comment]
@Stebalien let's make sure to spend some of the time together this week to write up the ROADMAP -- https://github.com/ipld/specs/blob/master/ROADMAP.md

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]
